{
 "title": "SPG",
 "tags": [ "spg" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "level", "label": "Level", "query": "INFO, WARNING, DEBUG, ERROR" }
  ]
 },
 "panels": [
  { "title": "Consultar métricas de negócio", "type": "dashlist", "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 } },
  { "title": "Golden Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total de requisições sucesso",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(flask_http_request_total{status=~\"2..\"}[$__range])))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Total de requisições Erro",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(flask_http_request_total{status!~\"2..\"}[$__range])))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Requisições por segundo",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Disponibilidade",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!~\"5..\"}[$__range])) / sum(rate(flask_http_request_duration_seconds_count[$__range]))",
     "legendFormat": "Disponibilidade"
    }
   ]
  },
  {
   "title": "% de Erros",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=~\"5..\"}[$__range])) / sum(rate(flask_http_request_duration_seconds_count[$__range]))",
     "legendFormat": "Disponibilidade"
    }
   ]
  },
  {
   "title": "Erros por segundo",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!=\"200\"}[2m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Tempo de resposta médio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{status=\"200\"}[2m])) by (path)\n/\nsum(rate(flask_http_request_duration_seconds_count{status=\"200\"}[2m])) by(path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Latencia Percentils",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(flask_http_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(flask_http_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(flask_http_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(flask_http_request_duration_seconds_bucket[2m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"case-app\"}",
     "legendFormat": "Memoria"
    }
   ]
  },
  {
   "title": "Utilizacao CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"case-app\"}[2m])",
     "legendFormat": "cpu"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total Logs por level",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(levelname) (count_over_time({service=\"case-app\"} | json | line_format \"\\\"levelname\\\":\\\"{{.levelname}}\\\"\" | __error__=`` [$__range]))",
     "legendFormat": "{{levelname}}"
    }
   ]
  },
  {
   "title": "Total de logs por metodo",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(funcName) (count_over_time({service=\"case-app\"} | json | line_format \"\\\"funcName\\\":\\\"{{.funcName}}\\\"\" | __error__=`` [$__range])))",
     "legendFormat": "{{funcName}}"
    }
   ]
  },
  {
   "title": "View General Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{service=\"case-app\"} |= `` | json | __error__=``| line_format \"{\\\"level\\\":\\\"{{.levelname}}\\\",\\\"message\\\":\\\"{{.message}}\\\",\\\"funcName\\\":\\\"{{.funcName}}\\\"}\" | json | level=~\"$level\""
    }
   ]
  }
 ]
}