groups:
- name: prometheus_node_exporter_rules
  rules:
  - expr: count without (cpu) (count without (mode) (node_cpu_seconds_total{job="node-exporter"}))
    record: instance:node_num_cpu:sum
  - expr: 1 - avg without (cpu, mode) (rate(node_cpu_seconds_total{job="node-exporter", mode="idle"}[1m]))
    record: instance:node_cpu_utilisation:rate1m
  - expr: (node_load1{job="node-exporter"} / instance:node_num_cpu:sum{job="node-exporter"})
    record: instance:node_load1_per_cpu:ratio
  - expr: 1 - (node_memory_MemAvailable_bytes{job="node-exporter"} / node_memory_MemTotal_bytes{job="node-exporter"})
    record: instance:node_memory_utilisation:ratio
  - expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)
    record: instance:node_memory_utilisation:percentage
  - expr: rate(node_vmstat_pgmajfault{job="node-exporter"}[1m])
    record: instance:node_vmstat_pgmajfault:rate1m
  - expr: rate(node_disk_io_time_seconds_total{job="node-exporter", device!=""}[1m])
    record: instance_device:node_disk_io_time_seconds:rate1m
  - expr: rate(node_disk_io_time_weighted_seconds_total{job="node-exporter", device!=""}[1m])
    record: instance_device:node_disk_io_time_weighted_seconds:rate1m
  - expr: sum without (device) (rate(node_network_receive_bytes_total{job="node-exporter", device!="lo"}[1m]))
    record: instance:node_network_receive_bytes_excluding_lo:rate1m
  - expr: sum without (device) (rate(node_network_transmit_bytes_total{job="node-exporter", device!="lo"}[1m]))
    record: instance:node_network_transmit_bytes_excluding_lo:rate1m
  - expr: sum without (device) (rate(node_network_receive_drop_total{job="node-exporter", device!="lo"}[1m]))
    record: instance:node_network_receive_drop_excluding_lo:rate1m
  - expr: sum without (device) (rate(node_network_transmit_drop_total{job="node-exporter", device!="lo"}[1m]))
    record: instance:node_network_transmit_drop_excluding_lo:rate1m

- name: sloth-slo-sli-recordings-case-app-requests-availability
  rules:
  - record: slo:sli_error:ratio_rate5m
    expr: |
      (sum(rate(flask_http_request_total{code=~"5.."}[5m])))
      /
      (sum(rate(flask_http_request_total[5m])))
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      sloth_window: 5m
      tier: "99"
  - record: slo:sli_error:ratio_rate30m
    expr: |
      (sum(rate(flask_http_request_total{code=~"5.."}[30m])))
      /
      (sum(rate(flask_http_request_total[30m])))
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      sloth_window: 30m
      tier: "99"
  - record: slo:sli_error:ratio_rate1h
    expr: |
      (sum(rate(flask_http_request_total{code=~"5.."}[1h])))
      /
      (sum(rate(flask_http_request_total[1h])))
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      sloth_window: 1h
      tier: "99"
  - record: slo:sli_error:ratio_rate2h
    expr: |
      (sum(rate(flask_http_request_total{code=~"5.."}[2h])))
      /
      (sum(rate(flask_http_request_total[2h])))
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      sloth_window: 2h
      tier: "99"
  - record: slo:sli_error:ratio_rate6h
    expr: |
      (sum(rate(flask_http_request_total{code=~"5.."}[6h])))
      /
      (sum(rate(flask_http_request_total[6h])))
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      sloth_window: 6h
      tier: "99"
  - record: slo:sli_error:ratio_rate1d
    expr: |
      (sum(rate(flask_http_request_total{code=~"5.."}[1d])))
      /
      (sum(rate(flask_http_request_total[1d])))
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      sloth_window: 1d
      tier: "99"
  - record: slo:sli_error:ratio_rate3d
    expr: |
      (sum(rate(flask_http_request_total{code=~"5.."}[3d])))
      /
      (sum(rate(flask_http_request_total[3d])))
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      sloth_window: 3d
      tier: "99"
  - record: slo:sli_error:ratio_rate30d
    expr: |
      sum_over_time(slo:sli_error:ratio_rate5m{sloth_id="case-app-requests-availability", sloth_service="case-app", sloth_slo="requests-availability"}[30d])
      / ignoring (sloth_window)
      count_over_time(slo:sli_error:ratio_rate5m{sloth_id="case-app-requests-availability", sloth_service="case-app", sloth_slo="requests-availability"}[30d])
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      sloth_window: 30d
      tier: "99"
- name: sloth-slo-meta-recordings-case-app-requests-availability
  rules:
  - record: slo:objective:ratio
    expr: vector(0.9990000000000001)
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      tier: "99"
  - record: slo:error_budget:ratio
    expr: vector(1-0.9990000000000001)
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      tier: "99"
  - record: slo:time_period:days
    expr: vector(30)
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      tier: "99"
  - record: slo:current_burn_rate:ratio
    expr: |
      slo:sli_error:ratio_rate5m{sloth_id="case-app-requests-availability", sloth_service="case-app", sloth_slo="requests-availability"}
      / on(sloth_id, sloth_slo, sloth_service) group_left
      slo:error_budget:ratio{sloth_id="case-app-requests-availability", sloth_service="case-app", sloth_slo="requests-availability"}
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      tier: "99"
  - record: slo:period_burn_rate:ratio
    expr: |
      slo:sli_error:ratio_rate30d{sloth_id="case-app-requests-availability", sloth_service="case-app", sloth_slo="requests-availability"}
      / on(sloth_id, sloth_slo, sloth_service) group_left
      slo:error_budget:ratio{sloth_id="case-app-requests-availability", sloth_service="case-app", sloth_slo="requests-availability"}
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      tier: "99"
  - record: slo:period_error_budget_remaining:ratio
    expr: 1 - slo:period_burn_rate:ratio{sloth_id="case-app-requests-availability",
      sloth_service="case-app", sloth_slo="requests-availability"}
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_service: case-app
      sloth_slo: requests-availability
      tier: "99"
  - record: sloth_slo_info
    expr: vector(1)
    labels:
      category: availability
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-availability
      sloth_mode: cli-gen-prom
      sloth_objective: "99.9"
      sloth_service: case-app
      sloth_slo: requests-availability
      sloth_spec: prometheus/v1
      sloth_version: v0.11.0
      tier: "99"
- name: sloth-slo-sli-recordings-case-app-requests-latency
  rules:
  - record: slo:sli_error:ratio_rate5m
    expr: |
      ((
        sum(rate(flask_http_request_duration_seconds_count[5m]))
        -
        sum(rate(flask_http_request_duration_seconds_bucket{le="1.0"}[5m]))
      )
      )
      /
      (sum(rate(apiserver_request_duration_seconds_count[5m])))
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      sloth_window: 5m
      tier: "99"
  - record: slo:sli_error:ratio_rate30m
    expr: |
      ((
        sum(rate(flask_http_request_duration_seconds_count[30m]))
        -
        sum(rate(flask_http_request_duration_seconds_bucket{le="1.0"}[30m]))
      )
      )
      /
      (sum(rate(apiserver_request_duration_seconds_count[30m])))
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      sloth_window: 30m
      tier: "99"
  - record: slo:sli_error:ratio_rate1h
    expr: |
      ((
        sum(rate(flask_http_request_duration_seconds_count[1h]))
        -
        sum(rate(flask_http_request_duration_seconds_bucket{le="1.0"}[1h]))
      )
      )
      /
      (sum(rate(apiserver_request_duration_seconds_count[1h])))
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      sloth_window: 1h
      tier: "99"
  - record: slo:sli_error:ratio_rate2h
    expr: |
      ((
        sum(rate(flask_http_request_duration_seconds_count[2h]))
        -
        sum(rate(flask_http_request_duration_seconds_bucket{le="1.0"}[2h]))
      )
      )
      /
      (sum(rate(apiserver_request_duration_seconds_count[2h])))
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      sloth_window: 2h
      tier: "99"
  - record: slo:sli_error:ratio_rate6h
    expr: |
      ((
        sum(rate(flask_http_request_duration_seconds_count[6h]))
        -
        sum(rate(flask_http_request_duration_seconds_bucket{le="1.0"}[6h]))
      )
      )
      /
      (sum(rate(apiserver_request_duration_seconds_count[6h])))
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      sloth_window: 6h
      tier: "99"
  - record: slo:sli_error:ratio_rate1d
    expr: |
      ((
        sum(rate(flask_http_request_duration_seconds_count[1d]))
        -
        sum(rate(flask_http_request_duration_seconds_bucket{le="1.0"}[1d]))
      )
      )
      /
      (sum(rate(apiserver_request_duration_seconds_count[1d])))
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      sloth_window: 1d
      tier: "99"
  - record: slo:sli_error:ratio_rate3d
    expr: |
      ((
        sum(rate(flask_http_request_duration_seconds_count[3d]))
        -
        sum(rate(flask_http_request_duration_seconds_bucket{le="1.0"}[3d]))
      )
      )
      /
      (sum(rate(apiserver_request_duration_seconds_count[3d])))
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      sloth_window: 3d
      tier: "99"
  - record: slo:sli_error:ratio_rate30d
    expr: |
      sum_over_time(slo:sli_error:ratio_rate5m{sloth_id="case-app-requests-latency", sloth_service="case-app", sloth_slo="requests-latency"}[30d])
      / ignoring (sloth_window)
      count_over_time(slo:sli_error:ratio_rate5m{sloth_id="case-app-requests-latency", sloth_service="case-app", sloth_slo="requests-latency"}[30d])
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      sloth_window: 30d
      tier: "99"
- name: sloth-slo-meta-recordings-case-app-requests-latency
  rules:
  - record: slo:objective:ratio
    expr: vector(0.99)
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      tier: "99"
  - record: slo:error_budget:ratio
    expr: vector(1-0.99)
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      tier: "99"
  - record: slo:time_period:days
    expr: vector(30)
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      tier: "99"
  - record: slo:current_burn_rate:ratio
    expr: |
      slo:sli_error:ratio_rate5m{sloth_id="case-app-requests-latency", sloth_service="case-app", sloth_slo="requests-latency"}
      / on(sloth_id, sloth_slo, sloth_service) group_left
      slo:error_budget:ratio{sloth_id="case-app-requests-latency", sloth_service="case-app", sloth_slo="requests-latency"}
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      tier: "99"
  - record: slo:period_burn_rate:ratio
    expr: |
      slo:sli_error:ratio_rate30d{sloth_id="case-app-requests-latency", sloth_service="case-app", sloth_slo="requests-latency"}
      / on(sloth_id, sloth_slo, sloth_service) group_left
      slo:error_budget:ratio{sloth_id="case-app-requests-latency", sloth_service="case-app", sloth_slo="requests-latency"}
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      tier: "99"
  - record: slo:period_error_budget_remaining:ratio
    expr: 1 - slo:period_burn_rate:ratio{sloth_id="case-app-requests-latency", sloth_service="case-app",
      sloth_slo="requests-latency"}
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_service: case-app
      sloth_slo: requests-latency
      tier: "99"
  - record: sloth_slo_info
    expr: vector(1)
    labels:
      category: latency
      owner: alanmetz
      repo: alanmetz/Case-Seguros
      sloth_id: case-app-requests-latency
      sloth_mode: cli-gen-prom
      sloth_objective: "99"
      sloth_service: case-app
      sloth_slo: requests-latency
      sloth_spec: prometheus/v1
      sloth_version: v0.11.0
      tier: "99"