version: "prometheus/v1"
service: "case-app"
labels:
  owner: "alanmetz"
  repo: "alanmetz/Case-Seguros"
  tier: "99"
slos:
  - name: "requests-availability"
    objective: 99.9
    description: "Warn that we are returning correctly the requests to the clients (kubectl users, controllers...)."
    labels:
      category: availability
    sli:
      events:
        error_query: sum(rate(flask_http_request_total{code=~"5.."}[{{.window}}]))
        total_query: sum(rate(flask_http_request_total[{{.window}}]))
    alerting:
      page_alert:
        disable: true
      ticket_alert:
        disable: true
  - name: "requests-latency"
    objective: 99
    description: "Warn that we apiserver responses are being slow and this will affect the clients  (kubectl users, controllers...)."
    labels:
      category: latency
    sli:
      events:
        error_query: |
          (
            sum(rate(flask_http_request_duration_seconds_count[{{.window}}]))
            -
            sum(rate(flask_http_request_duration_seconds_bucket{le="1.0"}[{{.window}}]))
          )
        total_query: sum(rate(apiserver_request_duration_seconds_count[{{.window}}]))
    alerting:
      page_alert:
        disable: true
      ticket_alert:
        disable: true

