apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    version: 1
    editable: true
    isDefault: true
  - name: Alertmanager
    type: alertmanager
    url: http://alertmanager:9093
    access: proxy
    jsonData:
      implementation: 'prometheus'
    basicAuth: false
    #basicAuthUser: my_user
    #basicAuthPassword: test_password
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false